### PR TITLE
Challenge-Scheme specific refresh-tokens

### PR DESCRIPTION
**Pull request by darrenschwarz**
As explained in issue #274, there are occasions when we need to manage tokens from more than one IDP and so need to be able to store and reference more than one refresh token.

### CODE REVIEW

**Comment by leastprivilege** [comment]
Why are there 30 changed files?

**Comment by darrenschwarz** [comment]
> Why are there 30 changed files?

There was a test project that I was using to validate. Which has now been removed. Now the changes are simply the ones to allow the refresh token behavior, and a couple with suggested rename, which if intended I can undo.

**Comment by darrenschwarz** [comment]
> Why are there 30 changed files?

@leastprivilege the focus of the PR should be clearer now :)

**Comment by brockallen** [comment]
@darrenschwarz do you feel that if someone upgraded to this version in an existing system that any existing tokens in the properties would be affected? IOW, is it backwards compat to upgrade live?

**Comment by darrenschwarz** [comment]
> 
Thank you for your timely response.

I think we should undoubtedly mitigate for that scenario. So assuming, in principle, you see the motivation underlying the PR, we could do something along the lines of:

```
var refreshTokenName = $"{TokenPrefix}{OpenIdConnectParameterNames.RefreshToken}";
if (!string.IsNullOrEmpty(parameters.ChallengeScheme) 
    && parameters.Context.ContainsKey("AppendChallengeSchemeToRefreshTokenName"))
{
    refreshTokenName += $"::{parameters.ChallengeScheme}";
}

```
Or take the value to append from the parameters.Context

```
var refreshTokenName = $"{TokenPrefix}{OpenIdConnectParameterNames.RefreshToken}";
if (parameters.Context.ContainsKey("AppendToRefreshTokenName"))
{
    refreshTokenName += $"::{parameters.Context.GetValues("AppendChallengeSchemeToRefreshTokenName").First()}";
}

```

I feel doing something like this would address the issue of backward compatibility and allow for a safe extension. 

If we did do either of the above, I'd point out that I would also want to raise a PR to extend the Duende.Bff.BffUserAccessTokenParameters to include:

```
        /// <summary>
        /// Additional context that might be relevant in the pipeline
        /// </summary>
        public Parameters Context { get; set; } = new();

```
Thoughts?

**Comment by darrenschwarz** [comment]
@brockallen I've updated the PR. Now addressing the question of backward compatibility.

```
string refreshToken = null;
var refreshTokenName = $"{TokenPrefix}{OpenIdConnectParameterNames.RefreshToken}";

if (!string.IsNullOrEmpty(parameters.ChallengeScheme))
{
    refreshToken = tokens.SingleOrDefault(t => t.Key == $"{refreshTokenName}::{parameters.ChallengeScheme}");
}

if (refreshToken == null)
{
    refreshToken = tokens.SingleOrDefault(t => t.Key == refreshTokenName );
}
```

**Comment by brockallen** [comment]
After having re-reviewed, isn't it possible that this API now returns an AT for one scheme and a RT for a diff scheme? Is this a concern? I'd almost expected the use of `ChallengeScheme` as a new prefix for all 3 of the entries in the props dictionary. Or am I missing something?

**Comment by brockallen** [comment]
Also, I'm a bit worried that the use of "::" as the delimiter for both resource and scheme now could get confused if there existed a resource id and scheme with the same values.

**Comment by darrenschwarz** [comment]
> After having re-reviewed, isn't it possible that this API now returns an AT for one scheme and a RT for a diff scheme? Is this a concern? I'd almost expected the use of `ChallengeScheme` as a new prefix for all 3 of the entries in the props dictionary. Or am I missing something?

I think the requirement described in [rfc8707 - name-access-token-request](https://www.rfc-editor.org/rfc/rfc8707.html#name-access-token-request) is possible with the current implementation.

Suffixing the RTs will allow for managing tokens from distinct IDPs.

As is the UserAccessTokenParameters allow for setting a Resource and Challenge scheme, and this covers the use-cases currently on my radar.

> Also, I'm a bit worried that the use of "::" as the delimiter for both resource and scheme now could get confused if there existed a resource id and scheme with the same values.

I have updated to make the delimiter for ChallengeScheme a ||.

**Comment by brockallen** [comment]
> Suffixing the RTs will allow for managing tokens from distinct IDPs.

This part I understand. But what I was saying is that it looks like with one call to this API specifying a ChallengeScheme that we can get a RT from one IdP (the one that matches the ChallengeScheme) and the AT from a different one (the default/empty one).

> this covers the use-cases currently on my radar.

I'm trying to imagine everyone else's to make for a consistent and understandable API :)

**Review by brockallen — APPROVED** [review]

**Pull request merged**
