### PR TITLE
User access token handler

### PR DESCRIPTION
**Pull request by zyofeng**
Fixed a small bug in the UserAccessTokenHandler where SignInScheme parameter is ignored and always uses DefaultScheme as a result.

Affecting applications using multiple authentication schemes.

### CODE REVIEW

**Comment by leastprivilege** [comment]
Maybe I am missing something - but the two lines are identical...

image

**Comment by zyofeng** [comment]
You are not assigning parameters to _parameters if it's being passed in.

**Comment by leastprivilege** [comment]
Oh sorry - yes - now I see ;) thanks!

**Comment by zyofeng** [comment]
Not a problem, is it possible to run a build so I don't have to use a forked version?

**Comment by leastprivilege** [comment]
done. thanks!

**Pull request merged**
